### ISSUE TITLE
生年月日入力欄について

### ISSUE THREAD

**Issue by YonezawaAkira** [caffisenna/rs100_v2#89]
## 起こっている問題 / The Problem
- 生年月日の年欄に1996より前の年が入力できない

## スクリーンショット / Screenshot
![image](https://github.com/caffisenna/rs100_v2/assets/134599753/ad67726a-eb61-47aa-897a-63a9a1fb5490)

## 期待する見せ方・挙動 / Expected Behavior
- オーバーエイジ対応のため、入力できるようお願いします

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://rsvp-rs100.scout.tokyo/user/entryForms/create

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by caffisenna** [comment]
2005年から1953年に拡張しました。(多すぎかも?)
